const arrows = document.querySelectorAll(".arrow");
console.log(arrows);
// !....................JAVASCRİPTTE BİRAZ İLERLEYİNCE....
// ! EVAM EDECEM ŞİMDİLİK BURDA KALSIN YOUTUBE BİLGİSAYAR.....
// ! GENETİĞİ ADLI YOUTUBE KANALINDA 1.50 SN DEN İTİBAREN ...
// ! İZLEMEYE DEVAM EDECEĞİM..